export const GET_ALL_FRUIT = "GET_ALL_FRUIT";
export const GET_ONE_FRUIT = "GET_ONE_FRUIT";
export const SHOW_GAME_DETAILS_MODAL = "SHOW_GAME_DETAILS_MODAL";
export const SHOW_SIGN_IN_MODAL = "SHOW_SIGN_IN_MODAL";
export const SHOW_SIGN_UP_MODAL = "SHOW_SIGN_UP_MODAL";